Created documentation for the new satellite data structure
censoredplanet/censoredplanet pull request #22
Opened 2022-05-10 17:40 UTC by eltsai

Created new documentation based on changes in the [public bucket](https://censoredplanet.org/data/raw)

2022-05-10 18:00 UTC, ramakrishnansr requested changes
I would also move this to the top of the documentation instead of the bottom.

2022-05-10 18:20 UTC, eltsai commented on docs/dns.rst
> +2. Separated the data collection phase and data analysis phase. Right now the Satellite data from our `public data bucket <https://data.censoredplanet.org/raw>`_ is truthful to the data collected wit
Updated

2022-05-10 21:52 UTC, ramakrishnansr requested changes
I think moving the newer data format to the top of the page is a good idea? Also, for the old schema, can we add `deprecated`?

2022-05-10 22:02 UTC, eltsai commented
Moved the new schema to the top and add `(deprecated)` after v1 and v2's schema

2022-05-11 00:42 UTC, ramakrishnansr approved these changes

2022-05-11 02:23 UTC, merged